language: rust
sudo: false
cache: cargo
rust:
  - 1.15.0
  - 1.16.0
  - stable
  - beta
  - nightly
  - nightly-2017-05-03
env:
  global:
    - NIGHTLY_VERSION=nightly-2017-05-03
    - CLIPPY_VERSION=0.0.131
    - RUST_BACKTRACE=1
before_script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$NIGHTLY_VERSION" ]]; then
      cargo install clippy --vers $CLIPPY_VERSION --force;
    fi'
script:
  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "$NIGHTLY_VERSION" ]]; then
      cargo clippy -- -D warnings;
    fi'
  - cargo doc --no-deps
  - cargo test --all
  - cargo test --all --release
matrix:
  allow_failures:
    - rust: nightly
    - rust: nightly-2017-05-03
